#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgeotiff
Version  : 1.5.1
Release  : 1
URL      : https://github.com/OSGeo/libgeotiff/releases/download/1.5.1/libgeotiff-1.5.1.tar.gz
Source0  : https://github.com/OSGeo/libgeotiff/releases/download/1.5.1/libgeotiff-1.5.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause BSD-4-Clause-UC MIT
Requires: libgeotiff-bin = %{version}-%{release}
Requires: libgeotiff-lib = %{version}-%{release}
Requires: libgeotiff-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : pkgconfig(libjpeg)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(proj)
BuildRequires : zlib-dev

%description
About LIBGEOTIFF:
-----------------
This library is designed to permit the extraction and parsing of the
"GeoTIFF" Key directories, as well as definition and installation
of GeoTIFF keys in new files. For more information about GeoTIFF
specifications, projection codes and use, see the WWW web page at:

%package bin
Summary: bin components for the libgeotiff package.
Group: Binaries

%description bin
bin components for the libgeotiff package.


%package dev
Summary: dev components for the libgeotiff package.
Group: Development
Requires: libgeotiff-lib = %{version}-%{release}
Requires: libgeotiff-bin = %{version}-%{release}
Provides: libgeotiff-devel = %{version}-%{release}
Requires: libgeotiff = %{version}-%{release}

%description dev
dev components for the libgeotiff package.


%package lib
Summary: lib components for the libgeotiff package.
Group: Libraries

%description lib
lib components for the libgeotiff package.


%package man
Summary: man components for the libgeotiff package.
Group: Default

%description man
man components for the libgeotiff package.


%prep
%setup -q -n libgeotiff-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1562010606
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --with-zlib --with-jpeg
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1562010606
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/applygeo
/usr/bin/geotifcp
/usr/bin/listgeo

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/epsg_datum.inc
/usr/include/epsg_ellipse.inc
/usr/include/epsg_gcs.inc
/usr/include/epsg_pcs.inc
/usr/include/epsg_pm.inc
/usr/include/epsg_proj.inc
/usr/include/epsg_units.inc
/usr/include/epsg_vertcs.inc
/usr/include/geo_ctrans.inc
/usr/include/geokeys.inc
/usr/lib64/libgeotiff.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgeotiff.so.5
/usr/lib64/libgeotiff.so.5.0.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/applygeo.1
/usr/share/man/man1/geotifcp.1
/usr/share/man/man1/listgeo.1
