#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgeotiff
Version  : 1.6.0
Release  : 4
URL      : https://github.com/OSGeo/libgeotiff/releases/download/1.6.0/libgeotiff-1.6.0.tar.gz
Source0  : https://github.com/OSGeo/libgeotiff/releases/download/1.6.0/libgeotiff-1.6.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause BSD-4-Clause-UC MIT
Requires: libgeotiff-bin = %{version}-%{release}
Requires: libgeotiff-lib = %{version}-%{release}
Requires: libgeotiff-license = %{version}-%{release}
Requires: libgeotiff-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : perl
BuildRequires : pkgconfig(libjpeg)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(proj)
BuildRequires : pkgconfig(zlib)

%description
About LIBGEOTIFF:
-----------------
This library is designed to permit the extraction and parsing of the
"GeoTIFF" Key directories, as well as definition and installation
of GeoTIFF keys in new files. For more information about GeoTIFF
specifications, projection codes and use, see the WWW web page at:

%package bin
Summary: bin components for the libgeotiff package.
Group: Binaries
Requires: libgeotiff-license = %{version}-%{release}

%description bin
bin components for the libgeotiff package.


%package dev
Summary: dev components for the libgeotiff package.
Group: Development
Requires: libgeotiff-lib = %{version}-%{release}
Requires: libgeotiff-bin = %{version}-%{release}
Provides: libgeotiff-devel = %{version}-%{release}
Requires: libgeotiff = %{version}-%{release}

%description dev
dev components for the libgeotiff package.


%package lib
Summary: lib components for the libgeotiff package.
Group: Libraries
Requires: libgeotiff-license = %{version}-%{release}

%description lib
lib components for the libgeotiff package.


%package license
Summary: license components for the libgeotiff package.
Group: Default

%description license
license components for the libgeotiff package.


%package man
Summary: man components for the libgeotiff package.
Group: Default

%description man
man components for the libgeotiff package.


%prep
%setup -q -n libgeotiff-1.6.0
cd %{_builddir}/libgeotiff-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588614020
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --with-zlib --with-jpeg
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1588614020
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libgeotiff
cp %{_builddir}/libgeotiff-1.6.0/LICENSE %{buildroot}/usr/share/package-licenses/libgeotiff/2e29d28d852441934f65ecc51e9ee3704c188432
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/applygeo
/usr/bin/geotifcp
/usr/bin/listgeo

%files dev
%defattr(-,root,root,-)
/usr/include/cpl_serv.h
/usr/include/epsg_datum.inc
/usr/include/epsg_ellipse.inc
/usr/include/epsg_gcs.inc
/usr/include/epsg_pcs.inc
/usr/include/epsg_pm.inc
/usr/include/epsg_proj.inc
/usr/include/epsg_units.inc
/usr/include/epsg_vertcs.inc
/usr/include/geo_config.h
/usr/include/geo_ctrans.inc
/usr/include/geo_keyp.h
/usr/include/geo_normalize.h
/usr/include/geo_simpletags.h
/usr/include/geo_tiffp.h
/usr/include/geokeys.h
/usr/include/geokeys.inc
/usr/include/geokeys_v1_1.inc
/usr/include/geonames.h
/usr/include/geotiff.h
/usr/include/geotiffio.h
/usr/include/geovalues.h
/usr/include/xtiffio.h
/usr/lib64/libgeotiff.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgeotiff.so.5
/usr/lib64/libgeotiff.so.5.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgeotiff/2e29d28d852441934f65ecc51e9ee3704c188432

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/applygeo.1
/usr/share/man/man1/geotifcp.1
/usr/share/man/man1/listgeo.1
